### PR TITLE
feat: add actions-box functionality

### PR DESCRIPTION
**Pull request by jpmckearin**
[bootstrap-select](https://github.com/silviomoreto/bootstrap-select) offers an, albeit [undocumented](https://github.com/silviomoreto/bootstrap-select/issues/825), option to add select all/deselect all buttons to the select picker. I needed the functionality for a project and thought I would share the implementation.

### CODE REVIEW

**Comment by jpmckearin** [comment]
I need more coffee...

**Comment by lordfriend** [comment]
This feature need a document before release. So it may take time for future test and document.

**Comment by capesean** [comment]
How do you make the actions box show? Is it an attribute or a class or something else?

**Comment by lordfriend** [comment]
Hi! @capesean document is here http://nya.io/nya-bootstrap-select/#!/examples/actions-box

**Pull request merged**
