### PR TITLE
Fixed IE scroll bug

### PR DESCRIPTION
**Pull request by MrWook**
Fixed scroll bug but would change the markup for #78 and #164

### CODE REVIEW

**Comment by lordfriend** [comment]
Did you test ngDisabled in this case? ngDisabled is an Angular directive which set `disabled` attribute on the host element. in this case using ngDisabled does nothing different with disabled.

https://github.com/angular/angular.js/blob/master/src/ng/directive/attrs.js

Besides, we have to maintain a backward compatibility so simplify remove support for disabled is not a good idea.

And update the document for a feature change is also required. 
http://nya.io/nya-bootstrap-select/#!/examples/form-control-feature

**Comment by MrWook** [comment]
Yes i updated my [plunker](https://plnkr.co/edit/vuaLhtJADChcpJFe0tS0?p=preview) #165 and `ngDisabled ` work just fine. 
The problem with `disabled ` is that the IE can't handle the expression inside of a standart attribute like `disabled.` This also applies to other standart attributes like  `class` or `style`. The [angular documentation](https://docs.angularjs.org/api/ng/directive/ngDisabled) say:
> A special directive is necessary because we cannot use interpolation inside the disabled attribute. See the interpolation guide for more info.

So it is neccessary to use the `ngDisabled`.
But what about to create a watcher for both attributes?

**Comment by lordfriend** [comment]
I think it is necessary to compatible with `disabled` attribute because a lot of old project use this, remove support for this will break those project.

If you remove the old `disabled` attribute support, ngDisabled works fine. but if you have investigated the source code of angular.js or observe the dom change on your plunk, ngDisabled actually maintain the attribute `disabled="disable"` on the nya-bs-select directive. which means it will create a mess when we intend to support both attribute for compatibility. 

So to support both attribute, we can first check if we have `ngDisabled` directive. we don't watch `disabled` when ngDisabled is available. otherwise, we check if we have disabled directive. we don't need watch both two attribute. User must use only one of the two attributes.

**Comment by MrWook** [comment]
It's true that the ngDisabled maintain the attribute disabled="disable". The problem is that the IE can't handle the expression right, inside of the attribute "disabled".

This is exactly what i meant with "both" i updated this PR and the [plunker](https://plnkr.co/edit/vuaLhtJADChcpJFe0tS0?p=preview)

**Pull request merged**
